services:
  - type: web
    name: ninerhub-backend
    env: python
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase: ninerhub-db
        property: connectionString
      - key: JWT_SECRET_KEY
        value: "a-very-secret-key-change-this"
databases:
  - name: ninerhub-db
    plan: free